# Generated by Django 4.1 on 2025-03-19 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('activity_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.activitylevel')),
            ],
        ),
    ]
