# Generated by Django 4.1 on 2025-03-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='macros',
            field=models.TextField(default=''),
        ),
    ]
