# Generated by Django 4.1 on 2025-03-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_userhistory_macros'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
