# Generated by Django 4.1 on 2025-03-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_userhistory_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
